### ISSUE TITLE
chrome 插件的登录状态一直是未登录，导致单词无法添加到单词本

### ISSUE THREAD

**Issue by loboxu** [wordway/wordway#20]
需要添加单词到单词本，浏览器登录后，chrome 插件一直显示未同步。截图如下：
![image](https://user-images.githubusercontent.com/32694291/95404718-61522200-0948-11eb-8558-a008364f32f2.png)
![image](https://user-images.githubusercontent.com/32694291/95404749-76c74c00-0948-11eb-9365-052546b5b3ed.png)

**Comment by lijy91** [comment]
插件升级导致该问题，已修复。
