### ISSUE TITLE
添加到生词本的功能有日程计划么？

### ISSUE THREAD

**Issue by entroxu** [wordway/wordway#21]
确认下还在继续开发么，日常有没有日程计划，添加到生词本的功能大约什么时候会发布？

**Comment by lijy91** [comment]
@entroxu 查词助手目前支持添加到生词本 https://github.com/wordway/extension/releases

**Comment by entroxu** [comment]
> @entroxu 查词助手目前支持添加到生词本 https://github.com/wordway/extension/releases

好的，谢谢回复，试了下，原因是自己没登录。

提些可优化的点：没登陆添加生词，没任何提示；插件中的登录没有引导，隐藏比较深。
