### ISSUE TITLE
How to Create Wordbook

### ISSUE THREAD

**Issue by lijy91** [wordway/wordway#3]
Please see [https://wordway.app/docs/how-to-create-wordbook](https://wordway.app/docs/how-to-create-wordbook).

**Comment by parse-dinghua** [comment]
@lijy91 请问如何设置单词本的封面？

**Comment by lijy91** [comment]
@parse-dinghua 在 `assets` 目录下添加 `cover.jpg` 文件即可，稍后我次这部分补充上去
