### ISSUE TITLE
Need a new wordbook

### ISSUE THREAD

**Issue by lijy91** [wordway/wordway#4]
# 需要一本新的单词本

我们希望在此收集大家对单词本的需求及建议，我们将根据大家的建议来增加官方维护的单词本。

**Comment by singworld** [comment]
单词本按书籍整理  比如把“Thinking in Java”这本书里的主要单词都整理出来背会  就可以看这本书了

**Comment by weikai21323** [comment]
能不能增加考研单词啊

**Comment by lijy91** [comment]
> 能不能增加考研单词啊

有相关推荐的吗？
